name: Sonoff M5 1-channel switch (M5-1C-80)
service: homeassistant
event_type: esphome
esphome_events:
  - switch_click
  - switch_double_click
  - switch_hold
identifier_key: device
buttons:
  - actions:
      - title: press
        conditions:
          - key: event_type
            value: switch_click
          - key: button
            value: middle
      - title: press 2x
        conditions:
          - key: event_type
            value: switch_double_click
          - key: button
            value: middle
      - title: hold
        conditions:
          - key: event_type
            value: switch_hold
          - key: button
            value: middle